version: '3'

tasks:
  stow:
    desc: "Re-store the home directory"
    cmds:
      - stow home -d "./" -t $HOME --adopt
  generate-zsh:
    desc: "Re-generate .zshrc"
    cmds:
      - $HOME/src/github.com/kalindudc/shell/src/generate_zshrc.rb
