set nocompatible

syntax on
colorscheme default
set list
set listchars=tab:!·,trail:·
set number

filetype plugin indent on
syntax on
runtime! config/**/*.vim

call plug#begin()

" On-demand loading
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Plugin outside ~/.vim/plugged with post-update hook
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

Plug 'chr4/nginx.vim'
Plug 'lepture/vim-jinja'

call plug#end()
