#!/usr/bin/env ruby
# typed: strict
# frozen_string_literal: true

# This script generates a zshrc file with the necessary aliases and functions using the
# provided .zshrc.erb template file. The generated zshrc file is saved to the
# provided output file path or to the default path if not provided.
#
# The .zshrc.erb template file should contain the following ERB tags:
#   - <%= base %>
#   - <%= aliases %>
#   - <%= git %>
#   - <%= functions %>
#   - <%= kubernetes %>
#   - <%= agents %>
#
# Usage: generate_zshrc [options]
#     -o, --output=OUTPUT_PATH         .zshrc output file path. Default path: ../home/.zshrc
#     -i, --input=INPUT_TEMPLATE       .zshrc.erb input template. Default path: ../src/templates/.zshrc.erb
#         --debug                      enable debug mode
#         --print                      output generated .zshrc to STDOUT
#

require 'erb'
require 'fileutils'
require 'optparse'
require 'logger'

DEFAULT_OUTPUT_PATH = "#{File.expand_path('..', File.dirname(__FILE__))}/home/.zshrc".freeze
DEFAULT_ZSHRC_TEMPLATE_PATH = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/.zshrc.erb".freeze

BASE_TEMPLATE = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/base.sh.erb".freeze
ZSH_CONFIG_TEMPLATE = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/zsh-config.sh.erb".freeze
ALIASES_TEMPLATE = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/aliases.sh.erb".freeze
GIT_TEMPLATE = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/git.sh.erb".freeze
FUNCTIONS_TEMPLATE = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/functions.sh.erb".freeze
KUBERNETES_TEMPLATE = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/kubernetes.sh.erb".freeze
AGENTS_TEMPLATE = "#{File.expand_path('.', File.dirname(__FILE__))}/templates/agents.sh.erb".freeze

def init
  @options = {
    output: DEFAULT_OUTPUT_PATH,
    zshrc_template: DEFAULT_ZSHRC_TEMPLATE_PATH,
    debug: false,
    print_output: false
  }

  OptionParser.new do |opt|
    opt.on('-oOUTPUT_PATH', '--output=OUTPUT_PATH', ".zshrc output file path. Default path: #{DEFAULT_OUTPUT_PATH}") { |o| @options[:output] = o }
    opt.on('-iINPUT_TEMPLATE', '--input=INPUT_TEMPLATE', ".zshrc.erb input template. Default path: #{DEFAULT_ZSHRC_TEMPLATE_PATH}") do |o|
      @options[:zshrc_template] = o
    end
    opt.on('--debug', 'enable debug mode') { |_o| @options[:debug] = true }
    opt.on('--print', 'output generated .zshrc to STDOUT') { |_o| @options[:print_output] = true }
  end.parse!

  # Verify the .zshrc.erb template file exists
  raise "Error: .zshrc.erb template file not found at #{@options[:zshrc_template]}" unless File.file?(@options[:zshrc_template])

  # Verify the output file path is writable
  raise "Error: Output file path #{@options[:output]} is not writable" unless File.writable?(@options[:output])

  @logger = Logger.new($stdout)
  @logger.level = if @options[:debug]
                    Logger::DEBUG
                  else
                    Logger::INFO
                  end
  @logger.info("Using options #{@options}")
end

def main
  init

  @logger.info("Rendering template #{BASE_TEMPLATE}")
  base_template_contents = render_template(BASE_TEMPLATE)

  @logger.info("Rendering template #{ZSH_CONFIG_TEMPLATE}")
  zsh_config_template_contents = render_template(ZSH_CONFIG_TEMPLATE)

  @logger.info("Rendering template #{ALIASES_TEMPLATE}")
  aliases_template_contents = render_template(ALIASES_TEMPLATE)

  @logger.info("Rendering template #{GIT_TEMPLATE}")
  git_template_contents = render_template(GIT_TEMPLATE)

  @logger.info("Rendering template #{FUNCTIONS_TEMPLATE}")
  functions_template_contents = render_template(FUNCTIONS_TEMPLATE)

  @logger.info("Rendering template #{KUBERNETES_TEMPLATE}")
  kubernetes_template_contents = render_template(KUBERNETES_TEMPLATE)

  @logger.info("Rendering template #{AGENTS_TEMPLATE}")
  agents_template_contents = render_template(AGENTS_TEMPLATE)

  misc_template_contents = <<~EOF
    if [[ "$(uname)" == "Linux" ]]; then
      # Use xclip to copy/paste to clipboard
      alias pbcopy='xclip -selection clipboard'
      alias pbpaste='xclip -selection clipboard -o'
    fi

    # Arch Linux: go-task package provides 'go-task' binary, alias to 'task'
    if [[ -f /etc/arch-release ]]; then
      alias task='go-task'
    fi
  EOF

  @logger.info("Rendering template #{@options[:zshrc_template]}")

  zshrc_template = File.read(@options[:zshrc_template])
  zshrc_erb = ERB.new(zshrc_template, trim_mode: '-')
  zshrc = zshrc_erb.result(binding)

  prefix = "# THIS FILE IS AUTO-GENERATED. DO NOT EDIT THIS FILE DIRECTLY.\n\n"
  zshrc_contents = prefix + zshrc

  if @options[:print_output]
    print "\n========================================\n\n"
    puts zshrc_contents
    print "\n========================================\n"
  else
    File.write(@options[:output], zshrc_contents)
    @logger.info("Generated .zshrc file saved to #{@options[:output]}")
  end

  # Generate zsh completions
  generate_completions
end

def generate_completions
  shell_dir = File.expand_path('..', File.dirname(__FILE__))
  completions_dir = File.join(shell_dir, 'home', '.config', 'zsh', 'completions')
  todo_bin = File.join(shell_dir, 'home', 'bin', 'todo')

  FileUtils.mkdir_p(completions_dir)

  if File.executable?(todo_bin)
    output = `#{todo_bin} --completions zsh 2>/dev/null`
    if $?.success? && !output.empty? # rubocop:disable Style/SpecialGlobalVars
      File.write(File.join(completions_dir, '_todo'), output)
      @logger.info("Generated zsh completions at #{completions_dir}/_todo")
    else
      @logger.warn('Failed to generate todo completions')
    end
  else
    @logger.warn("todo binary not found at #{todo_bin}, skipping completions")
  end

  # task or go-task provides the same completions, so we check for either one.
  # GO_TASK_EXE tells the completion script which command name to bind to.
  # If the binary is named 'task' we set GO_TASK_EXE=task so the generated
  # completion registers as `compdef _go_task task`, not `compdef _go_task go-task`.
  task_bin = `command -v task 2>/dev/null`.strip
  task_exe_name = task_bin.empty? ? 'go-task' : File.basename(task_bin)
  if task_bin.empty?
    task_bin = `command -v go-task 2>/dev/null`.strip
  end

  if !task_bin.empty? && File.executable?(task_bin)
    output = `#{task_bin} --completion zsh 2>/dev/null`
    if $?.success? && !output.empty? # rubocop:disable Style/SpecialGlobalVars
      # The completion script defaults to 'go-task' as the bound command name.
      # Two patches are required so `task<TAB>` works without completing `go_task` first:
      #
      # 1. Patch the runtime default so GO_TASK_CMD resolves to the actual binary.
      output = output.gsub('${GO_TASK_EXE:-go-task}', "${GO_TASK_EXE:-#{task_exe_name}}")
      #
      # 2. Patch the #compdef autoload header to include all command variants
      #    (go_task, task, go-task) so compinit registers completions for each.
      output = output.sub(/^(#compdef\s+go_task.*)$/, "\\1 task go-task")

      # 3. Add a _task() wrapper so the file works when autoloaded as _task.
      #    go-task generates _go_task() but compinit names the function after
      #    the file (_task). The wrapper delegates to the real implementation.
      output += "\n_task() { _go_task \"$@\" }\n"

      task_comp_file = File.join(completions_dir, '_task')
      File.write(task_comp_file, output)
      @logger.info("Generated zsh completions at #{task_comp_file}")

      # Clean up stale symlinks from previous versions of this script.
      ['_go-task', '_go_task'].each do |name|
        stale = File.join(completions_dir, name)
        FileUtils.rm_f(stale) if File.symlink?(stale)
      end

      # Invalidate the zcompdump cache so compinit picks up the new
      # #compdef mappings on the next shell start.
      zcompdump = File.join(Dir.home, '.zcompdump')
      FileUtils.rm_f(zcompdump) if File.exist?(zcompdump)
    else
      @logger.warn('Failed to generate task completions')
    end
  else
    @logger.warn('task binary not found, skipping task completions')
  end
end

def render_template(file_path)
  template = File.read(file_path)
  ERB.new(template, trim_mode: '-').result(binding)
end

main
