#!/usr/bin/env ruby
# frozen_string_literal: true

# Generates ~/.config/ghostty/config-os with an OS-specific font-size.
#
# Ghostty renders fonts smaller on macOS (CoreText) compared to Linux
# (FreeType) at the same point size. This script writes a small override
# config that is included from the main ghostty config via:
#
#   config-file = ?config-os
#
# Usage:
#   ruby src/generate_ghostty_config.rb [options]
#
# Options:
#   -o, --output=PATH   output path (default: ~/.config/ghostty/config-os)
#       --print         write to STDOUT, do not touch any file

require 'fileutils'
require 'optparse'
require 'logger'

DEFAULT_OUTPUT = File.expand_path('~/.config/ghostty/config-os').freeze

FONT_SIZES = {
  'macos' => 13,
  'linux' => 11
}.freeze

def detect_os
  return 'macos' if RUBY_PLATFORM.include?('darwin')

  return 'linux' if File.exist?('/etc/os-release')

  nil
end

def init
  @options = { output: DEFAULT_OUTPUT, print: false }

  OptionParser.new do |opt|
    opt.banner = 'Usage: generate_ghostty_config.rb [options]'
    opt.on('-oPATH', '--output=PATH',
           "Output path (default: #{DEFAULT_OUTPUT})") { |v| @options[:output] = v }
    opt.on('--print', 'Write to STDOUT, do not touch any file') { @options[:print] = true }
  end.parse!

  unless @options[:print]
    output_dir = File.dirname(@options[:output])
    FileUtils.mkdir_p(output_dir) unless File.directory?(output_dir)
  end

  @logger = Logger.new($stdout)
  @logger.level = Logger::INFO
  @logger.formatter = proc { |_sev, _dt, _prog, msg| "#{msg}\n" }
end

def main
  init

  os = detect_os
  abort('Unsupported operating system') unless os

  font_size = FONT_SIZES[os]

  contents = <<~CFG
    # Auto-generated by generate_ghostty_config.rb for #{os}
    # Edit #{@options[:output]} directly if you want a custom size.
    font-size = #{font_size}
  CFG

  if @options[:print]
    puts contents
  else
    File.write(@options[:output], contents)
    @logger.info("Generated #{@options[:output]} with font-size = #{font_size} (#{os})")
  end
end

main
